Repository SysKitTeam/docs-point, pull requests merged in 2025-06, with the labels that each got.

#867 Power BI reports - PP add-on please note added
  configuration/enable-powerBI-data-collection.md
  reporting/power-bi-reports.md
Labels: v2025.3.93

#875 saas release note 05.06
  SUMMARY.md
  releases/cloud/point-2025-06-05-release-note.md
Labels: v2025.3.94

#883 Point DC - 2025.3.95 - 17.06.2025.
  SUMMARY.md
  releases/data-center/syskit-point-2025-3/point-2025-3-95-release-note.md
Labels: DC, v2025.3.95

#888 Point Cloud - v2025.3.97 - 24.06.2025.
  SUMMARY.md
  releases/cloud/point-2025-06-24-release-note.md
  reporting/ai-agents-reports.md
Labels: v2025.3.97
