Repository SysKitTeam/docs-point, pull requests merged in 2025-07, with the labels that each got.

#890 DC release 0107
  SUMMARY.md
  releases/data-center/syskit-point-2025-3/point-2025-3-97-release-note.md
Labels: DC, v2025.3.97

#897 Point Cloud - v2025.3.98 - 01.07.2025.
  .gitbook/assets/dashboard-sharepoint-agents-tile.png
  SUMMARY.md
  microsoft365-inventory/explore-your-microsoft-365-dashboard.md
  releases/cloud/point-2025-07-01-release-note.md
Labels: v2025.3.98

#910 Point Data Center - v2025.3.99 - 15.07.2025.
  SUMMARY.md
  releases/data-center/syskit-point-2025-3/point-2025-3-99-release-note.md
Labels: DC, v2025.3.99

#926 Point DC - 2025.3.101 - 29.07.2025.
  SUMMARY.md
  releases/data-center/syskit-point-2025-3/point-2025-3-101-release-note.md
Labels: DC, v2025.3.101
